name: Publish beta release

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  snapshot:
    name: Publish beta release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --ignore-scripts

      - name: Build packages
        run: yarn build:packages
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Create snapshot versions
        run: npx changeset version --snapshot beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish snapshot to npm
        run: npx changeset publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
